apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
  namespace: netbox
data:
  TZ: "Asia/Tokyo"

  # DB
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "netbox"
  DB_USER: "netbox"

  # Redis（tasks と cache 両方を同じRedisにする）
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_CACHE_HOST: "redis"
  REDIS_CACHE_PORT: "6379"
