services:
  postgres:
    #image: postgres:13
    image: postgres:15
    container_name: netbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: netbox-redis
    restart: unless-stopped

  netbox:
    #image: netboxcommunity/netbox:v3.2.7
    #image: netboxcommunity/netbox:v3.5.9
    #image: netboxcommunity/netbox:v3.7.8
    #image: netboxcommunity/netbox:v4.0.11
    image: netboxcommunity/netbox:v4.5.1
    container_name: netbox
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      # ===== 必須設定 =====
      SECRET_KEY: "eKGT1mf8yk2MjEol6dJobnuKDOR8EpgyZ41G4hShQZLXbDZy8h80_6fiYH_UrcFkrU4"
      ALLOWED_HOSTS: "*"

      # ===== 管理ユーザー（初回のみ作成）=====
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_PASSWORD: admin

      # ===== Database =====
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: netbox
      DB_HOST: postgres
      DB_PORT: 5432

      # ===== Redis =====
      REDIS_HOST: redis
      REDIS_PORT: 6379

    volumes:
      - netbox_media:/opt/netbox/netbox/media
      - netbox_reports:/opt/netbox/netbox/reports
      - netbox_scripts:/opt/netbox/netbox/scripts

volumes:
  postgres_data:
  netbox_media:
  netbox_reports:
  netbox_scripts:
